config/routes.rb
TaskMobil::Application.routes.draw do
  resources :tasks
  post 'tasks/:id/start' => 'tasks#start'
  post 'tasks/:id/stop' => 'tasks#stop'

  resources :entries

  

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :task
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :entries   , :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:hours, :date, :category, :comment)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :start, :stop]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  def start
    @entry = Entry.new(:task_id => @task.id)

    respond_to do |format|
      if @entry.save
        format.js
      else
        format.js
      end
    end
  end

  def stop
    seconds = Time.now -  @task.entries.last.created_at
    @entry = @task.entries.last
    if @entry
      @entry.hours  = seconds
      @entry.date = Time.now()
      if @entry.save
        format.js
      end
    end
    format.js

  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
      format.js
    end
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
        format.js

      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
        format.js

      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hours %><br>
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Listing entries</h1>

<table>
  <thead>
    <tr>
      <th>Hours</th>
      <th>Date</th>
      <th>Category</th>
      <th>Comment</th>
      <th>Task Name</th>

      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.hours %></td>
        <td><%= entry.date.strftime("%d/%m/%Y %H:%M:%S") if entry.date %></td>
        <td><%= entry.category %></td>
        <td><%= entry.comment %></td>
        <td><%= entry.task.name if entry.task %></td>

        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hours:</strong>
  <%= @entry.hours %>
</p>

<p>
  <strong>Date:</strong>
  <%= @entry.date %>
</p>

<p>
  <strong>Category:</strong>
  <%= @entry.category %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @entry.comment %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Mtt" %></title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body class="<%= controller_name %> <%= action_name %>">

<style>
  .container {
      width:300px;

  }

</style>
<div id="main" role="main">
  <div class="container">
    <div class="content">
      <div class="row">
        <div class="span12">
          <%= yield %>
        </div>
      </div>
      <footer>
      </footer>
    </div>
  </div> <!--! end of .container -->
</div> <!--! end of #main -->
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task,:remote => true)  do |f| %>
    <% if @task.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

          <ul>
            <% @task.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.text_field :name, :placeholder => "Name task" %>

    <%= f.text_field :status, :placeholder => "Status task" %>
    <%= f.button "Post", :remote=>true, :type => "submit", :class => "btn btn-default" %>
<% end %>

app/views/tasks/_task.erb
<tr >
  <td><%= task.name %></td>
  <td id = "timer-<%=task.id %>"> 00:00:00 </td>
  <!--<td>-->
  <!--<% if task.status == 'closed' %>-->
      <!--<span class="label label-danger"><%= task.status %> </span>-->
      <!--<% else %>-->
      <!--<span class="label label-success"><%= task.status %> </span>-->
      <!--<% end %>-->

  <!--</td>-->
  <td>

    <%= link_to 'Start', {:action => :start, :id => task.id}, :method => :post,:remote=>true, :class => "btn btn-xs btn-success "%>
    <%= link_to 'Stop', {:action => :stop, :id => task.id}, :method => :post,:remote=>true, :onclick=>'stopTimer("timer-'+task.id.to_s+'")', :class => "btn btn-xs  btn-danger "%>
    <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/tasks/create.js.erb
<% if @task.errors.count == 0 %>

$('#new_task').remove();
$('#new_task_link').show();
$('#tasks').append('<%= j render("task", :task => @task) %>');

<% else %>

$('.new_task').remove();
$('#new_task_link').after('<%= j render("form") %>');

<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
    <h1>Listing tasks</h1>

    <table  class="table table-striped table-condensed">
      <thead>
        <tr>
          <th style="width:50%"></th>
          <!--<th>Status</th>-->
          <th></th>
          <th style="width:40%"></th>
        </tr>
      </thead>

      <tbody id="tasks">
        <% @tasks.each do |task| %>
             <%= render "task", :task => task %>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Task', new_task_path , :remote => true, :id => "new_task_link",  :class => "btn btn-primary"%>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/new.js.erb
$('#new_task_link').hide().after('<%= j render("form") %>');

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/start.js.erb
startTimer('timer-<%= @task.id %>');

app/views/tasks/stop.js.erb
stopTimer('timer-<%= @task.id %>');